[build-system]
requires = [
    "scikit-build-core",
    "numpy>=1.21",
]
build-backend = "scikit_build_core.build"

[project]
name = "pyglow"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = ["numpy>=1.21"]

[tool.scikit-build]
ninja.version = ">=1.10"
cmake.version = ">=3.17.2"
