!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.2.0)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_NEWmodel_getdims_nb(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => nb

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_nb
      subroutine f2py_NEWmodel_getdims_order(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => order

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_order
      subroutine f2py_NEWmodel_getdims_vnode(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => vnode

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_vnode
      subroutine f2py_NEWmodel_getdims_mparm(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => mparm

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_mparm
      subroutine f2py_NEWmodel_getdims_gfs(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gfs

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gfs
      subroutine f2py_NEWmodel_getdims_gfm(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gfm

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gfm
      subroutine f2py_NEWmodel_getdims_gfl(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gfl

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gfl
      subroutine f2py_NEWmodel_getdims_gvbar(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gvbar

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gvbar
      subroutine f2py_NEWmodel_getdims_gwbar(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gwbar

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gwbar
      subroutine f2py_NEWmodel_getdims_gbz(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gbz

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gbz
      subroutine f2py_NEWmodel_getdims_gbm(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gbm

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gbm
      subroutine f2py_NEWmodel_getdims_gzwght(r,s,f2pysetdata,flag)
      use NEWmodel, only: d => gzwght

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_NEWmodel_getdims_gzwght
      
      subroutine f2pyinitNEWmodel(f2pysetupfunc)
      use NEWmodel, only : nbf
      use NEWmodel, only : maxs
      use NEWmodel, only : maxm
      use NEWmodel, only : maxl
      use NEWmodel, only : maxn
      use NEWmodel, only : p
      use NEWmodel, only : nlev
      use NEWmodel, only : nnode
      use NEWmodel, only : alttns
      use NEWmodel, only : altsym
      use NEWmodel, only : altiso
      use NEWmodel, only : nb
      use NEWmodel, only : order
      use NEWmodel, only : vnode
      use NEWmodel, only : mparm
      use NEWmodel, only : gfs
      use NEWmodel, only : gfm
      use NEWmodel, only : gfl
      use NEWmodel, only : gvbar
      use NEWmodel, only : gwbar
      use NEWmodel, only : gbz
      use NEWmodel, only : gbm
      use NEWmodel, only : gzwght
      use NEWmodel, only : glev
      use NEWmodel, only : maxo
      use NEWmodel, only : cseason
      use NEWmodel, only : cwave
      use NEWmodel, only : ctide
      use NEWmodel, only : content
      use NEWmodel, only : component
      use NEWmodel, only : modelinit
      use NEWmodel, only : reset
      use NEWmodel, only : defaultdata
      external f2pysetupfunc
      external f2py_NEWmodel_getdims_nb
      external f2py_NEWmodel_getdims_order
      external f2py_NEWmodel_getdims_vnode
      external f2py_NEWmodel_getdims_mparm
      external f2py_NEWmodel_getdims_gfs
      external f2py_NEWmodel_getdims_gfm
      external f2py_NEWmodel_getdims_gfl
      external f2py_NEWmodel_getdims_gvbar
      external f2py_NEWmodel_getdims_gwbar
      external f2py_NEWmodel_getdims_gbz
      external f2py_NEWmodel_getdims_gbm
      external f2py_NEWmodel_getdims_gzwght
      call f2pysetupfunc(nbf,maxs,maxm,maxl,maxn,p,nlev,nnode,alttns,alt&
     &sym,altiso,f2py_NEWmodel_getdims_nb,f2py_NEWmodel_getdims_order,f2&
     &py_NEWmodel_getdims_vnode,f2py_NEWmodel_getdims_mparm,f2py_NEWmode&
     &l_getdims_gfs,f2py_NEWmodel_getdims_gfm,f2py_NEWmodel_getdims_gfl,&
     &f2py_NEWmodel_getdims_gvbar,f2py_NEWmodel_getdims_gwbar,f2py_NEWmo&
     &del_getdims_gbz,f2py_NEWmodel_getdims_gbm,f2py_NEWmodel_getdims_gz&
     &wght,glev,maxo,cseason,cwave,ctide,content,component,modelinit,res&
     &et,defaultdata)
      end subroutine f2pyinitNEWmodel

      
      subroutine f2pyinitvshengine(f2pysetupfunc)
      use vshengine, only : mmax
      use vshengine, only : nmax
      use vshengine, only : p0
      use vshengine, only : p1
      use vshengine, only : sf
      use vshengine, only : a
      use vshengine, only : b
      use vshengine, only : c
      use vshengine, only : d
      external f2pysetupfunc
      call f2pysetupfunc(mmax,nmax,p0,p1,sf,a,b,c,d)
      end subroutine f2pyinitvshengine

      subroutine f2py_apexcord_getdims_wk(r,s,f2pysetdata,flag)
      use apexcord, only: d => wk

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_apexcord_getdims_wk
      
      subroutine f2pyinitapexcord(f2pysetupfunc)
      use apexcord, only : xmiss
      use apexcord, only : glatlim
      use apexcord, only : precise
      use apexcord, only : datdmx
      use apexcord, only : datimx
      use apexcord, only : irlf
      use apexcord, only : kgma
      use apexcord, only : glalmn
      use apexcord, only : glalmx
      use apexcord, only : nla
      use apexcord, only : nlo
      use apexcord, only : nal
      use apexcord, only : lbx
      use apexcord, only : lby
      use apexcord, only : lbz
      use apexcord, only : lbv
      use apexcord, only : lla
      use apexcord, only : llo
      use apexcord, only : lal
      use apexcord, only : lwk
      use apexcord, only : wk
      use apexcord, only : colat
      use apexcord, only : elon
      use apexcord, only : vp
      use apexcord, only : ctp
      use apexcord, only : stp
      use apexcord, only : rtod
      use apexcord, only : dtor
      use apexcord, only : re
      use apexcord, only : req
      use apexcord, only : msgu
      use apexcord, only : pola
      use apexcord, only : io
      use apexcord, only : jo
      use apexcord, only : ko
      use apexcord, only : loaddata
      external f2pysetupfunc
      external f2py_apexcord_getdims_wk
      call f2pysetupfunc(xmiss,glatlim,precise,datdmx,datimx,irlf,kgma,g&
     &lalmn,glalmx,nla,nlo,nal,lbx,lby,lbz,lbv,lla,llo,lal,lwk,f2py_apex&
     &cord_getdims_wk,colat,elon,vp,ctp,stp,rtod,dtor,re,req,msgu,pola,i&
     &o,jo,ko,loaddata)
      end subroutine f2pyinitapexcord


