/* File: hwm07pymodule.c
 * This file is auto-generated with f2py (version:2.2.0).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Dec 23 14:13:07 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *hwm07py_error;
static PyObject *hwm07py_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_NEWmodel_def[] = {
  {"nbf",0,{{-1}},NPY_INT, 1},
  {"maxs",0,{{-1}},NPY_INT, 1},
  {"maxm",0,{{-1}},NPY_INT, 1},
  {"maxl",0,{{-1}},NPY_INT, 1},
  {"maxn",0,{{-1}},NPY_INT, 1},
  {"p",0,{{-1}},NPY_INT, 1},
  {"nlev",0,{{-1}},NPY_INT, 1},
  {"nnode",0,{{-1}},NPY_INT, 1},
  {"alttns",0,{{-1}},NPY_DOUBLE, 1},
  {"altsym",0,{{-1}},NPY_DOUBLE, 1},
  {"altiso",0,{{-1}},NPY_DOUBLE, 1},
  {"nb",1,{{-1}},NPY_INT, 1},
  {"order",2,{{-1,-1}},NPY_INT, 1},
  {"vnode",1,{{-1}},NPY_DOUBLE, 1},
  {"mparm",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gfs",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gfm",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gfl",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gvbar",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gwbar",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gbz",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gbm",2,{{-1,-1}},NPY_DOUBLE, 1},
  {"gzwght",1,{{-1}},NPY_DOUBLE, 1},
  {"glev",0,{{-1}},NPY_INT, 1},
  {"maxo",0,{{-1}},NPY_INT, 1},
  {"cseason",0,{{-1}},NPY_INT, 1},
  {"cwave",0,{{-1}},NPY_INT, 1},
  {"ctide",0,{{-1}},NPY_INT, 1},
  {"content",1,{{5}},NPY_INT, 1},
  {"component",1,{{2}},NPY_INT, 1},
  {"modelinit",0,{{-1}},NPY_INT, 1},
  {"reset",0,{{-1}},NPY_INT, 1},
  {"defaultdata",0,{{-1}},NPY_STRING, 128},
  {NULL}
};
static void f2py_setup_NEWmodel(char *nbf,char *maxs,char *maxm,char *maxl,char *maxn,char *p,char *nlev,char *nnode,char *alttns,char *altsym,char *altiso,void (*nb)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*order)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*vnode)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*mparm)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gfs)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gfm)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gfl)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gvbar)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gwbar)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gbz)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gbm)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*gzwght)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),char *glev,char *maxo,char *cseason,char *cwave,char *ctide,char *content,char *component,char *modelinit,char *reset,char *defaultdata) {
  int i_f2py=0;
  f2py_NEWmodel_def[i_f2py++].data = nbf;
  f2py_NEWmodel_def[i_f2py++].data = maxs;
  f2py_NEWmodel_def[i_f2py++].data = maxm;
  f2py_NEWmodel_def[i_f2py++].data = maxl;
  f2py_NEWmodel_def[i_f2py++].data = maxn;
  f2py_NEWmodel_def[i_f2py++].data = p;
  f2py_NEWmodel_def[i_f2py++].data = nlev;
  f2py_NEWmodel_def[i_f2py++].data = nnode;
  f2py_NEWmodel_def[i_f2py++].data = alttns;
  f2py_NEWmodel_def[i_f2py++].data = altsym;
  f2py_NEWmodel_def[i_f2py++].data = altiso;
  f2py_NEWmodel_def[i_f2py++].func = nb;
  f2py_NEWmodel_def[i_f2py++].func = order;
  f2py_NEWmodel_def[i_f2py++].func = vnode;
  f2py_NEWmodel_def[i_f2py++].func = mparm;
  f2py_NEWmodel_def[i_f2py++].func = gfs;
  f2py_NEWmodel_def[i_f2py++].func = gfm;
  f2py_NEWmodel_def[i_f2py++].func = gfl;
  f2py_NEWmodel_def[i_f2py++].func = gvbar;
  f2py_NEWmodel_def[i_f2py++].func = gwbar;
  f2py_NEWmodel_def[i_f2py++].func = gbz;
  f2py_NEWmodel_def[i_f2py++].func = gbm;
  f2py_NEWmodel_def[i_f2py++].func = gzwght;
  f2py_NEWmodel_def[i_f2py++].data = glev;
  f2py_NEWmodel_def[i_f2py++].data = maxo;
  f2py_NEWmodel_def[i_f2py++].data = cseason;
  f2py_NEWmodel_def[i_f2py++].data = cwave;
  f2py_NEWmodel_def[i_f2py++].data = ctide;
  f2py_NEWmodel_def[i_f2py++].data = content;
  f2py_NEWmodel_def[i_f2py++].data = component;
  f2py_NEWmodel_def[i_f2py++].data = modelinit;
  f2py_NEWmodel_def[i_f2py++].data = reset;
  f2py_NEWmodel_def[i_f2py++].data = defaultdata;
}
extern void F_FUNC(f2pyinitNEWmodel,F2PYINITNEWMODEL)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_NEWmodel(void) {
  F_FUNC(f2pyinitNEWmodel,F2PYINITNEWMODEL)(f2py_setup_NEWmodel);
}

static FortranDataDef f2py_vshengine_def[] = {
  {"mmax",0,{{-1}},NPY_INT, 1},
  {"nmax",0,{{-1}},NPY_INT, 1},
  {"p0",2,{{12,12}},NPY_DOUBLE, 1},
  {"p1",2,{{12,12}},NPY_DOUBLE, 1},
  {"sf",2,{{12,12}},NPY_DOUBLE, 1},
  {"a",2,{{12,12}},NPY_DOUBLE, 1},
  {"b",2,{{12,12}},NPY_DOUBLE, 1},
  {"c",2,{{12,12}},NPY_DOUBLE, 1},
  {"d",2,{{12,12}},NPY_DOUBLE, 1},
  {NULL}
};
static void f2py_setup_vshengine(char *mmax,char *nmax,char *p0,char *p1,char *sf,char *a,char *b,char *c,char *d) {
  int i_f2py=0;
  f2py_vshengine_def[i_f2py++].data = mmax;
  f2py_vshengine_def[i_f2py++].data = nmax;
  f2py_vshengine_def[i_f2py++].data = p0;
  f2py_vshengine_def[i_f2py++].data = p1;
  f2py_vshengine_def[i_f2py++].data = sf;
  f2py_vshengine_def[i_f2py++].data = a;
  f2py_vshengine_def[i_f2py++].data = b;
  f2py_vshengine_def[i_f2py++].data = c;
  f2py_vshengine_def[i_f2py++].data = d;
}
extern void F_FUNC(f2pyinitvshengine,F2PYINITVSHENGINE)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_vshengine(void) {
  F_FUNC(f2pyinitvshengine,F2PYINITVSHENGINE)(f2py_setup_vshengine);
}

static FortranDataDef f2py_apexcord_def[] = {
  {"xmiss",0,{{-1}},NPY_FLOAT, 1},
  {"glatlim",0,{{-1}},NPY_FLOAT, 1},
  {"precise",0,{{-1}},NPY_FLOAT, 1},
  {"datdmx",0,{{-1}},NPY_FLOAT, 1},
  {"datimx",0,{{-1}},NPY_FLOAT, 1},
  {"irlf",0,{{-1}},NPY_INT, 1},
  {"kgma",0,{{-1}},NPY_INT, 1},
  {"glalmn",0,{{-1}},NPY_FLOAT, 1},
  {"glalmx",0,{{-1}},NPY_FLOAT, 1},
  {"nla",0,{{-1}},NPY_INT, 1},
  {"nlo",0,{{-1}},NPY_INT, 1},
  {"nal",0,{{-1}},NPY_INT, 1},
  {"lbx",0,{{-1}},NPY_INT, 1},
  {"lby",0,{{-1}},NPY_INT, 1},
  {"lbz",0,{{-1}},NPY_INT, 1},
  {"lbv",0,{{-1}},NPY_INT, 1},
  {"lla",0,{{-1}},NPY_INT, 1},
  {"llo",0,{{-1}},NPY_INT, 1},
  {"lal",0,{{-1}},NPY_INT, 1},
  {"lwk",0,{{-1}},NPY_INT, 1},
  {"wk",1,{{-1}},NPY_FLOAT, 1},
  {"colat",0,{{-1}},NPY_FLOAT, 1},
  {"elon",0,{{-1}},NPY_FLOAT, 1},
  {"vp",0,{{-1}},NPY_FLOAT, 1},
  {"ctp",0,{{-1}},NPY_FLOAT, 1},
  {"stp",0,{{-1}},NPY_FLOAT, 1},
  {"rtod",0,{{-1}},NPY_FLOAT, 1},
  {"dtor",0,{{-1}},NPY_FLOAT, 1},
  {"re",0,{{-1}},NPY_FLOAT, 1},
  {"req",0,{{-1}},NPY_FLOAT, 1},
  {"msgu",0,{{-1}},NPY_FLOAT, 1},
  {"pola",0,{{-1}},NPY_FLOAT, 1},
  {"io",0,{{-1}},NPY_INT, 1},
  {"jo",0,{{-1}},NPY_INT, 1},
  {"ko",0,{{-1}},NPY_INT, 1},
  {"loaddata",0,{{-1}},NPY_INT, 1},
  {NULL}
};
static void f2py_setup_apexcord(char *xmiss,char *glatlim,char *precise,char *datdmx,char *datimx,char *irlf,char *kgma,char *glalmn,char *glalmx,char *nla,char *nlo,char *nal,char *lbx,char *lby,char *lbz,char *lbv,char *lla,char *llo,char *lal,char *lwk,void (*wk)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),char *colat,char *elon,char *vp,char *ctp,char *stp,char *rtod,char *dtor,char *re,char *req,char *msgu,char *pola,char *io,char *jo,char *ko,char *loaddata) {
  int i_f2py=0;
  f2py_apexcord_def[i_f2py++].data = xmiss;
  f2py_apexcord_def[i_f2py++].data = glatlim;
  f2py_apexcord_def[i_f2py++].data = precise;
  f2py_apexcord_def[i_f2py++].data = datdmx;
  f2py_apexcord_def[i_f2py++].data = datimx;
  f2py_apexcord_def[i_f2py++].data = irlf;
  f2py_apexcord_def[i_f2py++].data = kgma;
  f2py_apexcord_def[i_f2py++].data = glalmn;
  f2py_apexcord_def[i_f2py++].data = glalmx;
  f2py_apexcord_def[i_f2py++].data = nla;
  f2py_apexcord_def[i_f2py++].data = nlo;
  f2py_apexcord_def[i_f2py++].data = nal;
  f2py_apexcord_def[i_f2py++].data = lbx;
  f2py_apexcord_def[i_f2py++].data = lby;
  f2py_apexcord_def[i_f2py++].data = lbz;
  f2py_apexcord_def[i_f2py++].data = lbv;
  f2py_apexcord_def[i_f2py++].data = lla;
  f2py_apexcord_def[i_f2py++].data = llo;
  f2py_apexcord_def[i_f2py++].data = lal;
  f2py_apexcord_def[i_f2py++].data = lwk;
  f2py_apexcord_def[i_f2py++].func = wk;
  f2py_apexcord_def[i_f2py++].data = colat;
  f2py_apexcord_def[i_f2py++].data = elon;
  f2py_apexcord_def[i_f2py++].data = vp;
  f2py_apexcord_def[i_f2py++].data = ctp;
  f2py_apexcord_def[i_f2py++].data = stp;
  f2py_apexcord_def[i_f2py++].data = rtod;
  f2py_apexcord_def[i_f2py++].data = dtor;
  f2py_apexcord_def[i_f2py++].data = re;
  f2py_apexcord_def[i_f2py++].data = req;
  f2py_apexcord_def[i_f2py++].data = msgu;
  f2py_apexcord_def[i_f2py++].data = pola;
  f2py_apexcord_def[i_f2py++].data = io;
  f2py_apexcord_def[i_f2py++].data = jo;
  f2py_apexcord_def[i_f2py++].data = ko;
  f2py_apexcord_def[i_f2py++].data = loaddata;
}
extern void F_FUNC(f2pyinitapexcord,F2PYINITAPEXCORD)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_apexcord(void) {
  F_FUNC(f2pyinitapexcord,F2PYINITAPEXCORD)(f2py_setup_apexcord);
}
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/
/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "hwm07py",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_hwm07py(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = hwm07py_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module hwm07py (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.2.0");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'hwm07py' is auto-generated with f2py (version:2.2.0).\nFunctions:\n"
"Fortran 90/95 modules:\n""  NEWmodel --- nbf,maxs,maxm,maxl,maxn,p,nlev,nnode,alttns,altsym,altiso,nb,order,vnode,mparm,gfs,gfm,gfl,gvbar,gwbar,gbz,gbm,gzwght,glev,maxo,cseason,cwave,ctide,content,component,modelinit,reset,defaultdata""  vshengine --- mmax,nmax,p0,p1,sf,a,b,c,d""  apexcord --- xmiss,glatlim,precise,datdmx,datimx,irlf,kgma,glalmn,glalmx,nla,nlo,nal,lbx,lby,lbz,lbv,lla,llo,lal,lwk,wk,colat,elon,vp,ctp,stp,rtod,dtor,re,req,msgu,pola,io,jo,ko,loaddata"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.2.0");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    hwm07py_error = PyErr_NewException ("hwm07py.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_hwm07py_error", hwm07py_error);
    Py_DECREF(hwm07py_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }
/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "apexcord", PyFortranObject_New(f2py_apexcord_def,f2py_init_apexcord));  PyDict_SetItemString(d, "vshengine", PyFortranObject_New(f2py_vshengine_def,f2py_init_vshengine));  PyDict_SetItemString(d, "NEWmodel", PyFortranObject_New(f2py_NEWmodel_def,f2py_init_NEWmodel));/*eof initf90modhooks*/
/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"hwm07py");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
