C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.2.0)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapVTST7 (VTST7f2pywrap, IYD, SEC, GLAT, GLO
     &NG, STL, F107A, F107, AP, IC)
      external VTST7
      integer IYD
      real SEC
      real GLAT
      real GLONG
      real STL
      real F107A
      real F107
      integer IC
      real AP(7)
      real VTST7f2pywrap
      real  VTST7
      VTST7f2pywrap = VTST7(IYD, SEC, GLAT, GLONG, STL, F107A, F10
     &7, AP, IC)
      end


      subroutine f2pywrapSCALH (SCALHf2pywrap, ALT, XM, TEMP)
      external SCALH
      real ALT
      real XM
      real TEMP
      real SCALHf2pywrap
      real  SCALH
      SCALHf2pywrap = SCALH(ALT, XM, TEMP)
      end


      subroutine f2pywrapGLOBE7 (GLOBE7f2pywrap, YRD, SEC, LAT, LO
     &NG, TLOC, F107A, F107, AP, P)
      external GLOBE7
      real YRD
      real SEC
      real LAT
      real LONG
      real TLOC
      real F107A
      real F107
      real AP(7)
      real P(150)
      real GLOBE7f2pywrap
      real  GLOBE7
      GLOBE7f2pywrap = GLOBE7(YRD, SEC, LAT, LONG, TLOC, F107A, F1
     &07, AP, P)
      end


      subroutine f2pywrapGLOB7S (GLOB7Sf2pywrap, P)
      external GLOB7S
      real P(150)
      real GLOB7Sf2pywrap
      real  GLOB7S
      GLOB7Sf2pywrap = GLOB7S(P)
      end


      subroutine f2pywrapDENSU (DENSUf2pywrap, ALT, DLB, TINF, TLB
     &, XM, ALPHA, TZ, ZLB, S2, MN1, ZN1, TN1, TGN1)
      external DENSU
      real ALT
      real DLB
      real TINF
      real TLB
      real XM
      real ALPHA
      real TZ
      real ZLB
      real S2
      integer MN1
      real ZN1(MN1)
      real TN1(MN1)
      real TGN1(2)
      real DENSUf2pywrap
      real  DENSU
      DENSUf2pywrap = DENSU(ALT, DLB, TINF, TLB, XM, ALPHA, TZ, ZL
     &B, S2, MN1, ZN1, TN1, TGN1)
      end


      subroutine f2pywrapDENSM (DENSMf2pywrap, ALT, D0, XM, TZ, MN
     &3, ZN3, TN3, TGN3, MN2, ZN2, TN2, TGN2)
      external DENSM
      real ALT
      real D0
      real XM
      real TZ
      integer MN3
      integer MN2
      real ZN3(MN3)
      real TN3(MN3)
      real TGN3(2)
      real ZN2(MN2)
      real TN2(MN2)
      real TGN2(2)
      real DENSMf2pywrap
      real  DENSM
      DENSMf2pywrap = DENSM(ALT, D0, XM, TZ, MN3, ZN3, TN3, TGN3, 
     &MN2, ZN2, TN2, TGN2)
      end


      subroutine f2pywrapDNET (DNETf2pywrap, DD, DM, ZHM, XMM, XM)
      external DNET
      real DD
      real DM
      real ZHM
      real XMM
      real XM
      real DNETf2pywrap
      real  DNET
      DNETf2pywrap = DNET(DD, DM, ZHM, XMM, XM)
      end


      subroutine f2pywrapCCOR (CCORf2pywrap, ALT, R, H1, ZH)
      external CCOR
      real ALT
      real R
      real H1
      real ZH
      real CCORf2pywrap
      real  CCOR
      CCORf2pywrap = CCOR(ALT, R, H1, ZH)
      end


      subroutine f2pywrapCCOR2 (CCOR2f2pywrap, ALT, R, H1, ZH, H2)
      external CCOR2
      real ALT
      real R
      real H1
      real ZH
      real H2
      real CCOR2f2pywrap
      real  CCOR2
      CCOR2f2pywrap = CCOR2(ALT, R, H1, ZH, H2)
      end


      subroutine f2pywrapfmodip (fmodipf2pywrap, xlat)
      external fmodip
      real xlat
      real fmodipf2pywrap
      real  fmodip
      fmodipf2pywrap = fmodip(xlat)
      end


      subroutine f2pywrapOVL_ANG (OVL_ANGf2pywrap, sla, slo, cla, 
     &clo, rr)
      external OVL_ANG
      real sla
      real slo
      real cla
      real clo
      real rr
      real OVL_ANGf2pywrap
      real  OVL_ANG
      OVL_ANGf2pywrap = OVL_ANG(sla, slo, cla, clo, rr)
      end


      subroutine f2pywrapcgmgla (cgmglaf2pywrap, clon)
      external cgmgla
      real clon
      real cgmglaf2pywrap
      real  cgmgla
      cgmglaf2pywrap = cgmgla(clon)
      end


      subroutine f2pywrapcgmglo (cgmglof2pywrap, clon)
      external cgmglo
      real clon
      real cgmglof2pywrap
      real  cgmglo
      cgmglof2pywrap = cgmglo(clon)
      end


      subroutine f2pywrapDFRIDR (DFRIDRf2pywrap, func, x, h, err)
      external DFRIDR
      external func
      real x
      real h
      real err
      real DFRIDRf2pywrap
      real  DFRIDR
      DFRIDRf2pywrap = DFRIDR(func, x, h, err)
      end


      subroutine f2pywrapAZM_ANG (AZM_ANGf2pywrap, sla, slo, cla, 
     &pla, plo)
      external AZM_ANG
      real sla
      real slo
      real cla
      real pla
      real plo
      real AZM_ANGf2pywrap
      real  AZM_ANG
      AZM_ANGf2pywrap = AZM_ANG(sla, slo, cla, pla, plo)
      end


      subroutine f2pywrapXE1 (XE1f2pywrap, H)
      external XE1
      real H
      real XE1f2pywrap
      real  XE1
      XE1f2pywrap = XE1(H)
      end


      subroutine f2pywrapTOPQ (TOPQf2pywrap, h, No, hmax, Ho)
      external TOPQ
      real h
      real No
      real hmax
      real Ho
      real TOPQf2pywrap
      real  TOPQ
      TOPQf2pywrap = TOPQ(h, No, hmax, Ho)
      end


      subroutine f2pywrapZERO (ZEROf2pywrap, DELTA)
      external ZERO
      real DELTA
      real ZEROf2pywrap
      real  ZERO
      ZEROf2pywrap = ZERO(DELTA)
      end


      subroutine f2pywrapDXE1N (DXE1Nf2pywrap, H)
      external DXE1N
      real H
      real DXE1Nf2pywrap
      real  DXE1N
      DXE1Nf2pywrap = DXE1N(H)
      end


      subroutine f2pywrapXE2 (XE2f2pywrap, H)
      external XE2
      real H
      real XE2f2pywrap
      real  XE2
      XE2f2pywrap = XE2(H)
      end


      subroutine f2pywrapXE3_1 (XE3_1f2pywrap, H)
      external XE3_1
      real H
      real XE3_1f2pywrap
      real  XE3_1
      XE3_1f2pywrap = XE3_1(H)
      end


      subroutine f2pywrapXE4_1 (XE4_1f2pywrap, H)
      external XE4_1
      real H
      real XE4_1f2pywrap
      real  XE4_1
      XE4_1f2pywrap = XE4_1(H)
      end


      subroutine f2pywrapXE5 (XE5f2pywrap, H)
      external XE5
      real H
      real XE5f2pywrap
      real  XE5
      XE5f2pywrap = XE5(H)
      end


      subroutine f2pywrapXE6 (XE6f2pywrap, H)
      external XE6
      real H
      real XE6f2pywrap
      real  XE6
      XE6f2pywrap = XE6(H)
      end


      subroutine f2pywrapXE_1 (XE_1f2pywrap, H)
      external XE_1
      real H
      real XE_1f2pywrap
      real  XE_1
      XE_1f2pywrap = XE_1(H)
      end


      subroutine f2pywrapINTERP (INTERPf2pywrap, N, L, V, X, XOUT)
      external INTERP
      integer N
      integer L
      real XOUT
      real V(N)
      real X(N)
      real INTERPf2pywrap
      real  INTERP
      INTERPf2pywrap = INTERP(N, L, V, X, XOUT)
      end


      subroutine f2pywrapELTE (ELTEf2pywrap, H)
      external ELTE
      real H
      real ELTEf2pywrap
      real  ELTE
      ELTEf2pywrap = ELTE(H)
      end


      subroutine f2pywrapTEDE (TEDEf2pywrap, H, DEN, COV)
      external TEDE
      real H
      real DEN
      real COV
      real TEDEf2pywrap
      real  TEDE
      TEDEf2pywrap = TEDE(H, DEN, COV)
      end


      subroutine f2pywrapTI (TIf2pywrap, H)
      external TI
      real H
      real TIf2pywrap
      real  TI
      TIf2pywrap = TI(H)
      end


      subroutine f2pywrapRPID (RPIDf2pywrap, H, H0, N0, M, ST, ID,
     & XS)
      external RPID
      real H
      real H0
      real N0
      integer M
      real ST(5)
      integer ID(4)
      real XS(4)
      real RPIDf2pywrap
      real  RPID
      RPIDf2pywrap = RPID(H, H0, N0, M, ST, ID, XS)
      end


      subroutine f2pywrapRDNO (RDNOf2pywrap, H, HB, RDO2H, RDOH, R
     &NO)
      external RDNO
      real H
      real HB
      real RDO2H
      real RDOH
      real RNO
      real RDNOf2pywrap
      real  RDNO
      RDNOf2pywrap = RDNO(H, HB, RDO2H, RDOH, RNO)
      end


      subroutine f2pywrapINVDPC (INVDPCf2pywrap, FL, DIMO, B0, DIP
     &L, DTOR)
      external INVDPC
      real FL
      real DIMO
      real B0
      real DIPL
      real DTOR
      real INVDPCf2pywrap
      real  INVDPC
      INVDPCf2pywrap = INVDPC(FL, DIMO, B0, DIPL, DTOR)
      end


      subroutine f2pywrapFOUT (FOUTf2pywrap, XMODIP, XLATI, XLONGI
     &, UT, FF0)
      external FOUT
      real XMODIP
      real XLATI
      real XLONGI
      real UT
      real FF0(988)
      real FOUTf2pywrap
      real  FOUT
      FOUTf2pywrap = FOUT(XMODIP, XLATI, XLONGI, UT, FF0)
      end


      subroutine f2pywrapXMOUT (XMOUTf2pywrap, XMODIP, XLATI, XLON
     &GI, UT, XM0)
      external XMOUT
      real XMODIP
      real XLATI
      real XLONGI
      real UT
      real XM0(441)
      real XMOUTf2pywrap
      real  XMOUT
      XMOUTf2pywrap = XMOUT(XMODIP, XLATI, XLONGI, UT, XM0)
      end


      subroutine f2pywrapHMF2ED (HMF2EDf2pywrap, XMAGBR, R, X, XM3
     &)
      external HMF2ED
      real XMAGBR
      real R
      real X
      real XM3
      real HMF2EDf2pywrap
      real  HMF2ED
      HMF2EDf2pywrap = HMF2ED(XMAGBR, R, X, XM3)
      end


      subroutine f2pywrapXM3000HM (XM3000HMf2pywrap, XMAGBR, R, X,
     & HMF2)
      external XM3000HM
      real XMAGBR
      real R
      real X
      real HMF2
      real XM3000HMf2pywrap
      real  XM3000HM
      XM3000HMf2pywrap = XM3000HM(XMAGBR, R, X, HMF2)
      end


      subroutine f2pywrapFOF1ED (FOF1EDf2pywrap, YLATI, R, CHI)
      external FOF1ED
      real YLATI
      real R
      real CHI
      real FOF1EDf2pywrap
      real  FOF1ED
      FOF1EDf2pywrap = FOF1ED(YLATI, R, CHI)
      end


      subroutine f2pywrapf1_c1 (f1_c1f2pywrap, xmodip, hour, suxno
     &n, saxnon)
      external f1_c1
      real xmodip
      real hour
      real suxnon
      real saxnon
      real f1_c1f2pywrap
      real  f1_c1
      f1_c1f2pywrap = f1_c1(xmodip, hour, suxnon, saxnon)
      end


      subroutine f2pywrapFOEEDI (FOEEDIf2pywrap, COV, XHI, XHIM, X
     &LATI)
      external FOEEDI
      real COV
      real XHI
      real XHIM
      real XLATI
      real FOEEDIf2pywrap
      real  FOEEDI
      FOEEDIf2pywrap = FOEEDI(COV, XHI, XHIM, XLATI)
      end


      subroutine f2pywrapXMDED (XMDEDf2pywrap, XHI, R, YW)
      external XMDED
      real XHI
      real R
      real YW
      real XMDEDf2pywrap
      real  XMDED
      XMDEDf2pywrap = XMDED(XHI, R, YW)
      end


      subroutine f2pywrapGAMMA1 (GAMMA1f2pywrap, SMODIP, SLAT, SLO
     &NG, HOUR, IHARM, NQ, K1, M, MM, M3, SFE)
      external GAMMA1
      real SMODIP
      real SLAT
      real SLONG
      real HOUR
      integer IHARM
      integer K1
      integer M
      integer MM
      integer M3
      integer NQ(K1)
      real SFE(M3)
      real GAMMA1f2pywrap
      real  GAMMA1
      GAMMA1f2pywrap = GAMMA1(SMODIP, SLAT, SLONG, HOUR, IHARM, NQ
     &, K1, M, MM, M3, SFE)
      end


      subroutine f2pywrapB0_98 (B0_98f2pywrap, HOUR, SAX, SUX, NSE
     &ASN, R, ZLO, ZMODIP)
      external B0_98
      real HOUR
      real SAX
      real SUX
      integer NSEASN
      real R
      real ZLO
      real ZMODIP
      real B0_98f2pywrap
      real  B0_98
      B0_98f2pywrap = B0_98(HOUR, SAX, SUX, NSEASN, R, ZLO, ZMODIP
     &)
      end


      subroutine f2pywrapHPOL (HPOLf2pywrap, HOUR, TW, XNW, SA, SU
     &, DSA, DSU)
      external HPOL
      real HOUR
      real TW
      real XNW
      real SA
      real SU
      real DSA
      real DSU
      real HPOLf2pywrap
      real  HPOL
      HPOLf2pywrap = HPOL(HOUR, TW, XNW, SA, SU, DSA, DSU)
      end


      subroutine f2pywrapRLAY (RLAYf2pywrap, X, XM, SC, HX)
      external RLAY
      real X
      real XM
      real SC
      real HX
      real RLAYf2pywrap
      real  RLAY
      RLAYf2pywrap = RLAY(X, XM, SC, HX)
      end


      subroutine f2pywrapD1LAY (D1LAYf2pywrap, X, XM, SC, HX)
      external D1LAY
      real X
      real XM
      real SC
      real HX
      real D1LAYf2pywrap
      real  D1LAY
      D1LAYf2pywrap = D1LAY(X, XM, SC, HX)
      end


      subroutine f2pywrapD2LAY (D2LAYf2pywrap, X, XM, SC, HX)
      external D2LAY
      real X
      real XM
      real SC
      real HX
      real D2LAYf2pywrap
      real  D2LAY
      D2LAYf2pywrap = D2LAY(X, XM, SC, HX)
      end


      subroutine f2pywrapEPTR (EPTRf2pywrap, X, SC, HX)
      external EPTR
      real X
      real SC
      real HX
      real EPTRf2pywrap
      real  EPTR
      EPTRf2pywrap = EPTR(X, SC, HX)
      end


      subroutine f2pywrapEPST (EPSTf2pywrap, X, SC, HX)
      external EPST
      real X
      real SC
      real HX
      real EPSTf2pywrap
      real  EPST
      EPSTf2pywrap = EPST(X, SC, HX)
      end


      subroutine f2pywrapEPSTEP (EPSTEPf2pywrap, Y2, Y1, SC, HX, X
     &)
      external EPSTEP
      real Y2
      real Y1
      real SC
      real HX
      real X
      real EPSTEPf2pywrap
      real  EPSTEP
      EPSTEPf2pywrap = EPSTEP(Y2, Y1, SC, HX, X)
      end


      subroutine f2pywrapEPLA (EPLAf2pywrap, X, SC, HX)
      external EPLA
      real X
      real SC
      real HX
      real EPLAf2pywrap
      real  EPLA
      EPLAf2pywrap = EPLA(X, SC, HX)
      end


      subroutine f2pywrapXE2TO5 (XE2TO5f2pywrap, H, HMF2, NL, HX, 
     &SC, AMP)
      external XE2TO5
      real H
      real HMF2
      integer NL
      real HX(NL)
      real SC(NL)
      real AMP(NL)
      real XE2TO5f2pywrap
      real  XE2TO5
      XE2TO5f2pywrap = XE2TO5(H, HMF2, NL, HX, SC, AMP)
      end


      subroutine f2pywrapXEN (XENf2pywrap, H, HMF2, XNMF2, HME, NL
     &, HX, SC, AMP)
      external XEN
      real H
      real HMF2
      real XNMF2
      real HME
      integer NL
      real HX(NL)
      real SC(NL)
      real AMP(NL)
      real XENf2pywrap
      real  XEN
      XENf2pywrap = XEN(H, HMF2, XNMF2, HME, NL, HX, SC, AMP)
      end


      subroutine f2pywrapSTORME_AP (STORME_APf2pywrap, JDOY, XMLAT
     &, AP)
      external STORME_AP
      integer JDOY
      real XMLAT
      real AP
      real STORME_APf2pywrap
      real  STORME_AP
      STORME_APf2pywrap = STORME_AP(JDOY, XMLAT, AP)
      end


      subroutine f2pywrapbspl4_time (bspl4_timef2pywrap, i, x1)
      external bspl4_time
      integer i
      real x1
      real bspl4_timef2pywrap
      real  bspl4_time
      bspl4_timef2pywrap = bspl4_time(i, x1)
      end


      subroutine f2pywrapbspl4_long (bspl4_longf2pywrap, i, x1)
      external bspl4_long
      integer i
      real x1
      real bspl4_longf2pywrap
      real  bspl4_long
      bspl4_longf2pywrap = bspl4_long(i, x1)
      end


      subroutine f2pywrapbspl4_ptime (bspl4_ptimef2pywrap, i, x1)
      external bspl4_ptime
      integer i
      real x1
      real bspl4_ptimef2pywrap
      real  bspl4_ptime
      bspl4_ptimef2pywrap = bspl4_ptime(i, x1)
      end


      subroutine f2pywrapbspl4t (bspl4tf2pywrap, i, t1)
      external bspl4t
      integer i
      real t1
      real bspl4tf2pywrap
      real  bspl4t
      bspl4tf2pywrap = bspl4t(i, t1)
      end


      subroutine f2pywrapbspl2s (bspl2sf2pywrap, i, t1)
      external bspl2s
      integer i
      real t1
      real bspl2sf2pywrap
      real  bspl2s
      bspl2sf2pywrap = bspl2s(i, t1)
      end


      subroutine f2pywrapbspl2l (bspl2lf2pywrap, i, t1)
      external bspl2l
      integer i
      real t1
      real bspl2lf2pywrap
      real  bspl2l
      bspl2lf2pywrap = bspl2l(i, t1)
      end


      subroutine f2pywrapbspl2f (bspl2ff2pywrap, i, t1)
      external bspl2f
      integer i
      real t1
      real bspl2ff2pywrap
      real  bspl2f
      bspl2ff2pywrap = bspl2f(i, t1)
      end


      subroutine f2pywrapckp (ckpf2pywrap, ap)
      external ckp
      integer ap
      real ckpf2pywrap
      real  ckp
      ckpf2pywrap = ckp(ap)
      end


      subroutine f2pywrapioncorr (ioncorrf2pywrap, tec, f)
      external ioncorr
      real tec
      real f
      real ioncorrf2pywrap
      real  ioncorr
      ioncorrf2pywrap = ioncorr(tec, f)
      end


      subroutine f2pywrapT_XS_N2 (T_XS_N2f2pywrap, EP)
      external T_XS_N2
      real EP
      real T_XS_N2f2pywrap
      real  T_XS_N2
      T_XS_N2f2pywrap = T_XS_N2(EP)
      end


      subroutine f2pywrapT_XS_OX (T_XS_OXf2pywrap, EP)
      external T_XS_OX
      real EP
      real T_XS_OXf2pywrap
      real  T_XS_OX
      T_XS_OXf2pywrap = T_XS_OX(EP)
      end


      subroutine f2pyinitGTS3C(setupfunc)
      external setupfunc
      real TLB
      real S
      real DB04
      real DB16
      real DB28
      real DB32
      real DB40
      real DB48
      real DB01
      real ZA
      real T0
      real Z0
      real G0
      real RL
      real DD
      real DB14
      real TR12
      common /GTS3C/ TLB,S,DB04,DB16,DB28,DB32,DB40,DB48,DB01,ZA,T
     &0,Z0,G0,RL,DD,DB14,TR12
      call setupfunc(TLB,S,DB04,DB16,DB28,DB32,DB40,DB48,DB01,ZA,T
     &0,Z0,G0,RL,DD,DB14,TR12)
      end

      subroutine f2pyinitMESO7(setupfunc)
      external setupfunc
      real TN1(5)
      real TN2(4)
      real TN3(5)
      real TGN1(2)
      real TGN2(2)
      real TGN3(2)
      common /MESO7/ TN1,TN2,TN3,TGN1,TGN2,TGN3
      call setupfunc(TN1,TN2,TN3,TGN1,TGN2,TGN3)
      end

      subroutine f2pyinitLOWER7(setupfunc)
      external setupfunc
      real PTM(10)
      real PDM(10,8)
      common /LOWER7/ PTM,PDM
      call setupfunc(PTM,PDM)
      end

      subroutine f2pyinitPARM7(setupfunc)
      external setupfunc
      real PT(150)
      real PDA1(150)
      real PDA2(150)
      real PDA3(150)
      real PDA4(150)
      real PDA5(150)
      real PDA6(150)
      real PDA7(150)
      real PDA8(150)
      real PDA9(150)
      real PS(150)
      real PDL(25,2)
      real PTL(100,4)
      real PMA(100,10)
      real SAM(100)
      common /PARM7/ PT,PDA1,PDA2,PDA3,PDA4,PDA5,PDA6,PDA7,PDA8,PD
     &A9,PS,PDL,PTL,PMA,SAM
      call setupfunc(PT,PDA1,PDA2,PDA3,PDA4,PDA5,PDA6,PDA7,PDA8,PD
     &A9,PS,PDL,PTL,PMA,SAM)
      end

      subroutine f2pyinitDATIM7(setupfunc)
      external setupfunc
      character*4 ISD(3)
      character*4 IST(2)
      character*4 NAM(2)
      common /DATIM7/ ISD,IST,NAM
      call setupfunc(ISD,IST,NAM)
      end

      subroutine f2pyinitDATIME(setupfunc)
      external setupfunc
      character*4 ISDATE(3)
      character*4 ISTIME(2)
      character*4 NAME(2)
      common /DATIME/ ISDATE,ISTIME,NAME
      call setupfunc(ISDATE,ISTIME,NAME)
      end

      subroutine f2pyinitCSW(setupfunc)
      external setupfunc
      real SW(25)
      integer ISW
      real SWC(25)
      common /CSW/ SW,ISW,SWC
      call setupfunc(SW,ISW,SWC)
      end

      subroutine f2pyinitMAVG7(setupfunc)
      external setupfunc
      real PAVGM(10)
      common /MAVG7/ PAVGM
      call setupfunc(PAVGM)
      end

      subroutine f2pyinitDMIX(setupfunc)
      external setupfunc
      real DM04
      real DM16
      real DM28
      real DM32
      real DM40
      real DM01
      real DM14
      common /DMIX/ DM04,DM16,DM28,DM32,DM40,DM01,DM14
      call setupfunc(DM04,DM16,DM28,DM32,DM40,DM01,DM14)
      end

      subroutine f2pyinitPARMB(setupfunc)
      external setupfunc
      real GSURF
      real RE
      common /PARMB/ GSURF,RE
      call setupfunc(GSURF,RE)
      end

      subroutine f2pyinitMETSEL(setupfunc)
      external setupfunc
      integer IMR
      common /METSEL/ IMR
      call setupfunc(IMR)
      end

      subroutine f2pyinitTTEST(setupfunc)
      external setupfunc
      real TINFG
      real GB
      real ROUT
      real TT(15)
      common /TTEST/ TINFG,GB,ROUT,TT
      call setupfunc(TINFG,GB,ROUT,TT)
      end

      subroutine f2pyinitLPOLY(setupfunc)
      external setupfunc
      real PLG(9,4)
      real CTLOC
      real STLOC
      real C2TLOC
      real S2TLOC
      real C3TLOC
      real S3TLOC
      integer IYR
      real DAY
      real DF
      real DFA
      real APD
      real APDF
      real APT(4)
      real XLONG
      common /LPOLY/ PLG,CTLOC,STLOC,C2TLOC,S2TLOC,C3TLOC,S3TLOC,I
     &YR,DAY,DF,DFA,APD,APDF,APT,XLONG
      call setupfunc(PLG,CTLOC,STLOC,C2TLOC,S2TLOC,C3TLOC,S3TLOC,I
     &YR,DAY,DF,DFA,APD,APDF,APT,XLONG)
      end

      subroutine f2pyinitLSQV(setupfunc)
      external setupfunc
      integer MP
      integer II
      integer JG
      integer LT
      real QPB(50)
      integer IERR
      integer IFUN
      integer N
      integer J
      real DV(60)
      common /LSQV/ MP,II,JG,LT,QPB,IERR,IFUN,N,J,DV
      call setupfunc(MP,II,JG,LT,QPB,IERR,IFUN,N,J,DV)
      end

      subroutine f2pyinitFIT(setupfunc)
      external setupfunc
      real TAF
      common /FIT/ TAF
      call setupfunc(TAF)
      end

      subroutine f2pyinitIGRF1(setupfunc)
      external setupfunc
      real UMR
      real ERA
      real AQUAD
      real BQUAD
      common /IGRF1/ UMR,ERA,AQUAD,BQUAD
      call setupfunc(UMR,ERA,AQUAD,BQUAD)
      end

      subroutine f2pyinitIGRF2(setupfunc)
      external setupfunc
      real X(3)
      real H(196)
      common /IGRF2/ X,H
      call setupfunc(X,H)
      end

      subroutine f2pyinitFIDB0(setupfunc)
      external setupfunc
      real SP(3)
      common /FIDB0/ SP
      call setupfunc(SP)
      end

      subroutine f2pyinitMODEL(setupfunc)
      external setupfunc
      integer NMAX
      real TIME
      real G(196)
      character*13 NAME
      common /MODEL/ NMAX,TIME,G,NAME
      call setupfunc(NMAX,TIME,G,NAME)
      end

      subroutine f2pyinitDIPOL(setupfunc)
      external setupfunc
      real GHI1
      real GHI2
      real GHI3
      common /DIPOL/ GHI1,GHI2,GHI3
      call setupfunc(GHI1,GHI2,GHI3)
      end

      subroutine f2pyinitiounit(setupfunc)
      external setupfunc
      integer konsol
      common /iounit/ konsol
      call setupfunc(konsol)
      end

      subroutine f2pyinitCONST(setupfunc)
      external setupfunc
      real UMR
      common /CONST/ UMR
      call setupfunc(UMR)
      end

      subroutine f2pyinitfindRLAT(setupfunc)
      external setupfunc
      real xlong
      real year
      common /findRLAT/ xlong,year
      call setupfunc(xlong,year)
      end

      subroutine f2pyinitIYR(setupfunc)
      external setupfunc
      integer IYR
      common /IYR/ IYR
      call setupfunc(IYR)
      end

      subroutine f2pyinitNM(setupfunc)
      external setupfunc
      integer NM
      common /NM/ NM
      call setupfunc(NM)
      end

      subroutine f2pyinitcgmgeo(setupfunc)
      external setupfunc
      real clat
      logical cr360
      logical cr0
      real rh
      common /cgmgeo/ clat,cr360,cr0,rh
      call setupfunc(clat,cr360,cr0,rh)
      end

      subroutine f2pyinitA5(setupfunc)
      external setupfunc
      real DS3
      common /A5/ DS3
      call setupfunc(DS3)
      end

      subroutine f2pyinitC1(setupfunc)
      external setupfunc
      real ST0
      real CT0
      real SL0
      real CL0
      real CTCL
      real STCL
      real CTSL
      real STSL
      real SFI
      real CFI
      real SPS
      real CPS
      real SHI
      real CHI
      real HI
      real PSI
      real XMUT
      real A11
      real A21
      real A31
      real A12
      real A22
      real A32
      real A13
      real A23
      real A33
      real DS3
      integer K
      integer IY
      real BA(8)
      common /C1/ ST0,CT0,SL0,CL0,CTCL,STCL,CTSL,STSL,SFI,CFI,SPS,
     &CPS,SHI,CHI,HI,PSI,XMUT,A11,A21,A31,A12,A22,A32,A13,A23,A33,DS3,K,
     &IY,BA
      call setupfunc(ST0,CT0,SL0,CL0,CTCL,STCL,CTSL,STSL,SFI,CFI,S
     &PS,CPS,SHI,CHI,HI,PSI,XMUT,A11,A21,A31,A12,A22,A32,A13,A23,A33,DS3
     &,K,IY,BA)
      end

      subroutine f2pyinitFIRCOM(setupfunc)
      external setupfunc
      real EDEN(81,5,12,12,3)
      real TABHE(81)
      real TABLA(5)
      real TABMO(12)
      real TABZA(12)
      real TABFL(3)
      common /FIRCOM/ EDEN,TABHE,TABLA,TABMO,TABZA,TABFL
      call setupfunc(EDEN,TABHE,TABLA,TABMO,TABZA,TABFL)
      end

      subroutine f2pyinitBLOCK1(setupfunc)
      external setupfunc
      real HMF2
      real XNMF2
      real HMF1
      real F1REG
      common /BLOCK1/ HMF2,XNMF2,HMF1,F1REG
      call setupfunc(HMF2,XNMF2,HMF1,F1REG)
      end

      subroutine f2pyinitBLO10(setupfunc)
      external setupfunc
      real BETA
      real ETA
      real DELTA
      real ZETA
      common /BLO10/ BETA,ETA,DELTA,ZETA
      call setupfunc(BETA,ETA,DELTA,ZETA)
      end

      subroutine f2pyinitBLO11(setupfunc)
      external setupfunc
      real B2TOP
      real TC3
      integer itopn
      real alg10
      real hcor1
      common /BLO11/ B2TOP,TC3,itopn,alg10,hcor1
      call setupfunc(B2TOP,TC3,itopn,alg10,hcor1)
      end

      subroutine f2pyinitQTOP(setupfunc)
      external setupfunc
      real Y05
      real H05TOP
      real QF
      real XNETOP
      real xm3000
      real hhalf
      real tau
      common /QTOP/ Y05,H05TOP,QF,XNETOP,xm3000,hhalf,tau
      call setupfunc(Y05,H05TOP,QF,XNETOP,xm3000,hhalf,tau)
      end

      subroutine f2pyinitARGEXP(setupfunc)
      external setupfunc
      real ARGMAX
      common /ARGEXP/ ARGMAX
      call setupfunc(ARGMAX)
      end

      subroutine f2pyinitBLOCK2(setupfunc)
      external setupfunc
      real B0
      real B1
      real C1
      common /BLOCK2/ B0,B1,C1
      call setupfunc(B0,B1,C1)
      end

      subroutine f2pyinitBLOCK3(setupfunc)
      external setupfunc
      real HZ
      real T
      real HST
      common /BLOCK3/ HZ,T,HST
      call setupfunc(HZ,T,HST)
      end

      subroutine f2pyinitBLOCK4(setupfunc)
      external setupfunc
      real HME
      real XNME
      real HEF
      common /BLOCK4/ HME,XNME,HEF
      call setupfunc(HME,XNME,HEF)
      end

      subroutine f2pyinitBLOCK5(setupfunc)
      external setupfunc
      logical NIGHT
      real E(4)
      common /BLOCK5/ NIGHT,E
      call setupfunc(NIGHT,E)
      end

      subroutine f2pyinitBLOCK6(setupfunc)
      external setupfunc
      real HMD
      real XNMD
      real HDX
      common /BLOCK6/ HMD,XNMD,HDX
      call setupfunc(HMD,XNMD,HDX)
      end

      subroutine f2pyinitBLOCK7(setupfunc)
      external setupfunc
      real D1
      real XKK
      real FP30
      real FP3U
      real FP1
      real FP2
      common /BLOCK7/ D1,XKK,FP30,FP3U,FP1,FP2
      call setupfunc(D1,XKK,FP30,FP3U,FP1,FP2)
      end

      subroutine f2pyinitconst1(setupfunc)
      external setupfunc
      real humr
      real dumr
      common /const1/ humr,dumr
      call setupfunc(humr,dumr)
      end

      subroutine f2pyinitBLOTE(setupfunc)
      external setupfunc
      real AH(7)
      real ATE1
      real ST(6)
      real D(5)
      common /BLOTE/ AH,ATE1,ST,D
      call setupfunc(AH,ATE1,ST,D)
      end

      subroutine f2pyinitBLOCK8(setupfunc)
      external setupfunc
      real HS
      real TNHS
      real XSM(4)
      real MM(5)
      real G(4)
      integer M
      common /BLOCK8/ HS,TNHS,XSM,MM,G,M
      call setupfunc(HS,TNHS,XSM,MM,G,M)
      end

      subroutine f2pyinitconst(setupfunc)
      external setupfunc
      real umr
      common /const/ umr
      call setupfunc(umr)
      end

      subroutine f2pyinitargexp(setupfunc)
      external setupfunc
      real argmax
      common /argexp/ argmax
      call setupfunc(argmax)
      end

      subroutine f2pyinit_BLNK_(setupfunc)
      external setupfunc
      real BINT(7,7,5)
      real BEXT(7,7,5)
      real RE
      real TZERO
      integer IFIT
      integer IB
      integer KINT
      integer LINT
      integer KEXT
      integer LEXT
      integer KMAX
      real FN(7,7)
      common BINT,BEXT,RE,TZERO,IFIT,IB,KINT,LINT,KEXT,LEXT,KMAX,F
     &N
      call setupfunc(BINT,BEXT,RE,TZERO,IFIT,IB,KINT,LINT,KEXT,LEX
     &T,KMAX,FN)
      end

      subroutine f2pyinitmflux(setupfunc)
      external setupfunc
      integer kf
      integer n
      common /mflux/ kf,n
      call setupfunc(kf,n)
      end

      subroutine f2pyinitconst2(setupfunc)
      external setupfunc
      integer icalls
      integer nmono
      integer iyearo
      integer idaynro
      logical rzino
      logical igino
      real ut0
      common /const2/ icalls,nmono,iyearo,idaynro,rzino,igino,ut0
      call setupfunc(icalls,nmono,iyearo,idaynro,rzino,igino,ut0)
      end

      subroutine f2pyinitblock1(setupfunc)
      external setupfunc
      real hmf2
      real xnmf2
      real hmf1
      logical f1reg
      common /block1/ hmf2,xnmf2,hmf1,f1reg
      call setupfunc(hmf2,xnmf2,hmf1,f1reg)
      end

      subroutine f2pyinitEUVPRD(setupfunc)
      external setupfunc
      real EUVION(3,12)
      real PEXCIT(3,12)
      real PEPION(3,12)
      real OTHPR1(6)
      real OTHPR2(6)
      common /EUVPRD/ EUVION,PEXCIT,PEPION,OTHPR1,OTHPR2
      call setupfunc(EUVION,PEXCIT,PEPION,OTHPR1,OTHPR2)
      end

      subroutine f2pyinitSOL(setupfunc)
      external setupfunc
      real UVFAC(59)
      real EUV
      common /SOL/ UVFAC,EUV
      call setupfunc(UVFAC,EUV)
      end

      subroutine f2pyinitSIGS(setupfunc)
      external setupfunc
      real ZFLUX(37)
      real SIGABS(3,37)
      real ZLAM(37)
      real SIGION(3,37)
      real TPOT(3,10)
      integer NNI(3)
      real LAMAX
      common /SIGS/ ZFLUX,SIGABS,ZLAM,SIGION,TPOT,NNI,LAMAX
      call setupfunc(ZFLUX,SIGABS,ZLAM,SIGION,TPOT,NNI,LAMAX)
      end


